site_name: Sodero Documents

theme:
  name: material
  features:
    - navigation.expand
  palette:
  - scheme: slate
    primary: blue
    accent: cyan

nav:
  - Home: index.md
  - Stellar X:
    - What is Stellar X: stellarx/what_is_stellarx.md
    - Quick Start: stellarx/quick_start.md
    - Tutorials:
      - Stellar Designer:
        - About Stellar Deigner: stellarx/tutorials/stellar_designer/about_stellar_designer.md
        - 1. Kinematic Structure: stellarx/tutorials/stellar_designer/define_kinematic_structure.md
        - 2. Configure System Parameters: stellarx/tutorials/stellar_designer/configure_system_parameters.md
        - 3. Map Actuators: stellarx/tutorials/stellar_designer/map_actuators.md
        - 4. Verify Configuration: stellarx/tutorials/stellar_designer/verify_configuration.md
        - Start from Templates: stellarx/tutorials/stellar_designer/start_from_templates.md
      - Stellar Motion:
        - About Stellar Motion: stellarx/tutorials/stellar_motion/about_stellar_motion.md


